// Code generated by "stringer -type=Operation"; DO NOT EDIT.

package encrypt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpEncrypt-1]
	_ = x[OpDecrypt-2]
}

const _Operation_name = "OpEncryptOpDecrypt"

var _Operation_index = [...]uint8{0, 9, 18}

func (i Operation) String() string {
	i -= 1
	if i < 0 || i >= Operation(len(_Operation_index)-1) {
		return "Operation(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Operation_name[_Operation_index[i]:_Operation_index[i+1]]
}
